language: php

php:
- 7.1
- 7.2

before_script:
- composer install

cache:
  directories:
  - $HOME/.composer/cache/files

script:
- vendor/bin/php-cs-fixer fix --dry-run --diff
- vendor/bin/phpunit --configuration phpunit.xml.dist